### ISSUE TITLE
`read-only` flag in `EncryptedFs`

### ISSUE THREAD

**Issue by radumarias** [xoriors/rencfs#168]
Similar to https://github.com/radumarias/rencfs/issues/95 but add this also in `EncryptedFs`

Add also some tests.

shoud return `Err`:

- copy_file_range
- create
- create_write
- create_write_seek
- flush
- open(write = true)
- passwd
- remove_dir
- remove_file
- rename
- set_attr
- set_len
- write

**Comment by radumarias** [comment]
@someotherself is this merge yet? or some tests remaining?

**Comment by someotherself** [comment]
@radumarias Yes, and I missed some methods as well. Will add them soon.
create_write
create_write_seek
passwd
set_attr

**Comment by radumarias** [comment]
thank you

**Comment by radumarias** [comment]
@someotherself how's it going with this?

**Comment by someotherself** [comment]
@radumarias Should we close this?

**Comment by radumarias** [comment]
> @radumarias Should we close this?

is there anything left to do?

**Comment by someotherself** [comment]
No. We merged this. I forgot to link the PR to the issue.

**Comment by someotherself** [comment]
@radumarias No. We merged this. I forgot to link the PR to the issue.
