### ISSUE TITLE
Split readme file

### ISSUE THREAD

**Issue by radumarias** [xoriors/rencfs#225]
Have something like https://github.com/tock/tock

Create dedicated pages and have links from readme.

Introduction
* Motivation
* A Short Story
* Blog and Tutorial
* Talks
* Crate of the Week

Features
* Key Features
* GUI
* Alternatives

Implementation
* Functionality
* Stack

Documentation

Usage and Development
* Usage
* Build from Source
* Minimum Supported Rust Version

Future and Considerations
* Future
* Performance
* Security
* Considerations

Contribute

**Comment by IoanaAlexandraO** [comment]
Would you assign my issue, I don't have access rights?

**Comment by radumarias** [comment]
@IoanaAlexandraO please accept the invite then you'll be able to https://github.com/radumarias/rencfs/invitations
