### ISSUE TITLE
Zeroize password in java-bridge after first read

### ISSUE THREAD

**Issue by radumarias** [xoriors/rencfs#88]
https://github.com/radumarias/rencfs/blob/main/java-bridge/src/lib.rs#L121

Keep it in `SecretVec<u8>` and call `drop(pass)` after you use it.

Fix this too https://github.com/radumarias/ciphershell-kotlin/issues/56

**Comment by radumarias** [comment]
https://github.com/radumarias/rencfs/pull/250

**Comment by radumarias** [comment]
@misespuneraul asta e gata? il pot inchide?

**Comment by misespuneraul** [comment]
yes, thanks


Trimis din Yahoo Mail pentru iPhone


La joi, decembrie 12, 2024, 12:00 a.m., Radu Marias ***@***.***> a scris:




@misespuneraul asta e gata? il pot inchide?

**Comment by radumarias** [comment]
merged
